# -*- coding: utf-8 -*-
"""Heart_attack.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EbbN54MTvCGKw-HyzN6piO3-StuEGLPz
"""

import pandas as pd

df = pd.read_csv('heart.csv')

df

import numpy as np

df.isnull().sum()



df.head()

df.describe()

df.nunique()

df.output.value_counts()

df['age'].mean()

df.chol.max()

val = df[(df['output']==1) & (df['sex']==1)]
print("for serious case in men ",{len(val)})
val2 = df[(df['output']==1) & (df['sex']==0)]
print("for serious case in women ",{len(val2)})

import matplotlib.pyplot as plt
import seaborn as sns

analysis_cols = [col for col in df.columns if col != "output"]
fig, axes = plt.subplots(nrows=len(analysis_cols), ncols=2, figsize=(12, 60))

for index, col in enumerate(analysis_cols):
    sns.histplot(df[df["output"] == 0][col], color="blue", alpha=0.7, ax=axes[index, 0])
    axes[index, 0].set_xlabel(str(col))
    axes[index, 0].set_ylabel('Frequency')
    axes[index, 0].set_title(f'Histograms for {col} - Output 0')
    sns.histplot(df[df["output"] == 1][col], color="red", alpha=0.7, ax=axes[index, 1])
    axes[index, 1].set_xlabel(str(col))
    axes[index, 1].set_ylabel('Frequency')
    axes[index, 1].set_title(f'Histograms for {col} - Output 1')

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt

fig, axes = plt.subplots(len(df.columns), 1, figsize=(8, 25))

for i, col in enumerate(df.columns):
    axes[i].boxplot(df[col], vert=False)
    axes[i].set_title(col, fontsize=12)

plt.xlabel("Data Values")
plt.ylabel("Features")
plt.tight_layout()

plt.show()

cor = df.corr()
plt.figure(figsize =  (12,9))
sns.heatmap(cor, annot = True)

dfcp = df[df['cp'] == 0]
cp_asymptomatic = dfcp['output'].value_counts()
cp_asymptomatic

#link of dataframe

#https://www.kaggle.com/datasets/rashikrahmanpritom/heart-attack-analysis-prediction-dataset/data