# -*- coding: utf-8 -*-
"""Solution Matplotlib_Exercises.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rn0-0kDzB0Wl7mX87VTyeLCIdRXYw_Y2

# Matplotlib Exercises

Welcome to the exercises for reviewing matplotlib! Take your time with these, Matplotlib can be tricky to understand at first. These are relatively simple plots, but they can be hard if this is your first time with matplotlib, feel free to ask about anything as you go along.

Also don't worry if you find the matplotlib syntax frustrating, we actually won't be using it that often, we will switch to using seaborn and pandas built-in visualization capabilities. But, those are built-off of matplotlib, which is why it is still important to get exposure to it!

** * NOTE: ALL THE COMMANDS FOR PLOTTING A FIGURE SHOULD ALL GO IN THE SAME CELL. SEPARATING THEM OUT INTO MULTIPLE CELLS MAY CAUSE NOTHING TO SHOW UP. * **

# Exercises

Follow the instructions to recreate the plots using this data:

## Data
"""

import numpy as np
x = np.arange(0,100)
y = x*2
z = x**2

"""** Import matplotlib.pyplot as plt and set %matplotlib inline if you are using the jupyter notebook. What command do you use if you aren't using the jupyter notebook?**"""

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
# %matplotlib inline

"""## Exercise 1

** Follow along with these steps: **
* ** Create a figure object called fig using plt.figure() **
* ** Use add_axes to add an axis to the figure canvas at [0,0,1,1]. Call this new axis ax. **
* ** Plot (x,y) on that axes and set the labels and titles to match the plot below:**
"""

fig = plt.figure()
ax = fig.add_axes([0,0,1,1])
ax.plot(x,y)
ax.set_xlabel('x')
ax.set_ylabel('y')
ax.set_title('title')

"""## Exercise 2
** Create a figure object and put two axes on it, ax1 and ax2. Located at [0,0,1,1] and [0.2,0.5,.2,.2] respectively.**
"""

fig = plt.figure()
ax1 = fig.add_axes([0,0,1,1])
ax2 = fig.add_axes([0.2,0.5,.2,.2])

"""** Now plot (x,y) on both axes. And call your figure object to show it.**"""

fig = plt.figure()
ax1 = fig.add_axes([0,0,1,1])
ax2 = fig.add_axes([0.2,0.5,.2,.2])
ax1.plot(x,y,'r')
ax2.plot(x,y,'r')
plt.show()

"""## Exercise 3

** Create the plot below by adding two axes to a figure object at [0,0,1,1] and [0.2,0.5,.4,.4]**
"""

fig = plt.figure()
Ax1 = fig.add_axes([0,0,1,1])
Ax2 = fig.add_axes([0.2,0.5,.4,.4])

"""** Now use x,y, and z arrays to recreate the plot below. Notice the xlimits and y limits on the inserted plot:**"""

fig = plt.figure()

ax1 = fig.add_axes([0,0,1,1])
ax2 = fig.add_axes( [0.2,0.5,.4,.4])
ax2.plot(x,y)
ax2.set_xlim(20,22)#here
ax2.set_ylim(30,50)#here

ax2.set_xlabel('x')
ax2.set_ylabel('y')
ax2.set_title('zoom')

ax1.plot(x,z)
ax1.set_xlabel('x')
ax1.set_xlabel('z')

ax3 = fig.add_axes([0,-1.2,1,1])
ax4 = fig.add_axes( [0.2,-0.7,.4,.4])
ax4.plot(x,y)
ax4.set_ylim(30,50)
ax4.set_xlim(20,22)
ax4.set_title('zoom')
ax4.set_xlabel('x')
ax4.set_ylabel('y')

ax3.plot(x,z)
ax3.set_xlabel('x')
ax3.set_xlabel('z')

"""## Exercise 4

** Use plt.subplots(nrows=1, ncols=2) to create the plot below.**
"""

fig = plt.figure()
x1 = fig.add_subplot(1,2,1)
x2 = fig.add_subplot(1,2,2)

"""** Now plot (x,y) and (x,z) on the axes. Play around with the linewidth and style**"""

fig = plt.figure()
x1 = fig.add_subplot(1,2,1)
x2 = fig.add_subplot(1,2,2)
x1.plot(x,y,'b--')
x2.plot(x,z,'r')

"""** See if you can resize the plot by adding the figsize() argument in plt.subplots() are copying and pasting your previous code.**"""

fig = plt.figure(figsize=(25,5))
x1 = fig.add_subplot(1,2,1)
x2 = fig.add_subplot(1,2,2)
x1.plot(x,y,'b')
x2.plot(x,z,'r--')

"""# Great Job!

## #shAI Club
"""