# -*- coding: utf-8 -*-
"""copy of Pandas__Exercises.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ucnWYwYu2IuAU8n6xXwyuOQtJBJ1qHiv

___

<a href='http://www.pieriandata.com'> <img src='../../Pierian_Data_Logo.png' /></a>
___

# SF Salaries Exercise

Welcome to a quick exercise for you to practice your pandas skills! We will be using the [SF Salaries Dataset](https://www.kaggle.com/kaggle/sf-salaries) from Kaggle! Just follow along and complete the tasks outlined in bold below. The tasks will get harder and harder as you go along.

** Import pandas as pd.**
"""

import pandas as pd

"""** Read Salaries.csv as a dataframe called sal.**"""

df = pd.read_csv('Salaries(exercise).csv')

"""** Check the head of the DataFrame. **"""

df.head()

"""**What is the average BasePay ?**"""

df['BasePay'].mean()

"""** What is the highest amount of OvertimePay in the dataset ? **"""

df['OvertimePay'].max()

"""** What is the job title of  JOSEPH DRISCOLL ? Note: Use all caps, otherwise you may get an answer that doesn't match up (there is also a lowercase Joseph Driscoll). **"""

val =df[df['EmployeeName']=='JOSEPH DRISCOLL']

val['JobTitle']

"""** How much does JOSEPH DRISCOLL make (including benefits)? **"""

val['TotalPayBenefits']

"""** What is the name of highest paid person (including benefits)?**"""

Max = df['TotalPayBenefits'].max()
df[df['TotalPayBenefits']==Max]

"""** What is the name of lowest paid person (including benefits)? Do you notice something strange about how much he or she is paid?**"""

Min = df['TotalPayBenefits'].min()
df[df['TotalPayBenefits']==Min]
#he pays for working LOL, not possible(useless)

"""** What was the average (mean) BasePay of all employees per year? (2011-2014) ? **"""

print('Year')
grouped = df.groupby('Year')['BasePay'].mean()
grouped

"""** How many unique job titles are there? **

Read about the "nunique" function
"""

job = df['JobTitle']
job.nunique()

"""** What are the top 5 most common jobs? **"""

most = df['JobTitle'].value_counts()
most.head()

"""** **bold text** How many Job Titles were represented by only one person in 2013? (e.g. Job Titles with only one occurence in 2013?) **"""



df_2013 = df[df['Year'] == 2013]
job_title_counts = df_2013['JobTitle'].value_counts()
unique_job_titles = (job_title_counts == 1).sum()
unique_job_titles

"""** How many people have the word Chief

---

in their job title? (This is pretty tricky) **
"""



chief = df[df['JobTitle'].str.contains('Chief', case=False)]
total_chief = len(chief)
total_chief

# ans is 627

""" Is there a correlation between length of the Job Title string and Salary? **"""

df['Job Title Length'] = df['JobTitle'].apply(len)
correlation_matrix = df[['Job Title Length', 'TotalPayBenefits']].corr()

correlation_matrix

"""# Great Job!"""